//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace TestService.FrameService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FramesDataWsSoap", Namespace="http://www.framesdata.com/FDWS/")]
    public partial class FramesDataWs : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FDWSQuickSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetStyleByCollectionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSAuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSAuthenticateForPMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetStyleColorsByStyleIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetStyleConfigurationsByStyleIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSgetStylesByIDsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetStyleConfigurationUpdatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetStylePropertiesByStyleIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetCollectionsByBrandIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetBrandsByManufacturerIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetManufacturersOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetAgeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetGenderOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetProductGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetMaterialOperationCompleted;
        
        private System.Threading.SendOrPostCallback FDWSGetColorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FramesDataWs() {
            this.Url = global::TestService.Properties.Settings.Default.TestService_FrameService_FramesDataWs;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FDWSQuickSearchCompletedEventHandler FDWSQuickSearchCompleted;
        
        /// <remarks/>
        public event FDWSGetStyleByCollectionIDCompletedEventHandler FDWSGetStyleByCollectionIDCompleted;
        
        /// <remarks/>
        public event FDWSAuthenticateCompletedEventHandler FDWSAuthenticateCompleted;
        
        /// <remarks/>
        public event FDWSAuthenticateForPMSCompletedEventHandler FDWSAuthenticateForPMSCompleted;
        
        /// <remarks/>
        public event FDWSGetStyleColorsByStyleIDCompletedEventHandler FDWSGetStyleColorsByStyleIDCompleted;
        
        /// <remarks/>
        public event FDWSGetStyleConfigurationsByStyleIDCompletedEventHandler FDWSGetStyleConfigurationsByStyleIDCompleted;
        
        /// <remarks/>
        public event FDWSgetStylesByIDsCompletedEventHandler FDWSgetStylesByIDsCompleted;
        
        /// <remarks/>
        public event FDWSGetStyleConfigurationUpdatesCompletedEventHandler FDWSGetStyleConfigurationUpdatesCompleted;
        
        /// <remarks/>
        public event FDWSGetStylePropertiesByStyleIDCompletedEventHandler FDWSGetStylePropertiesByStyleIDCompleted;
        
        /// <remarks/>
        public event FDWSGetCollectionsByBrandIDCompletedEventHandler FDWSGetCollectionsByBrandIDCompleted;
        
        /// <remarks/>
        public event FDWSGetBrandsByManufacturerIDCompletedEventHandler FDWSGetBrandsByManufacturerIDCompleted;
        
        /// <remarks/>
        public event FDWSGetManufacturersCompletedEventHandler FDWSGetManufacturersCompleted;
        
        /// <remarks/>
        public event FDWSGetAgeCompletedEventHandler FDWSGetAgeCompleted;
        
        /// <remarks/>
        public event FDWSGetGenderCompletedEventHandler FDWSGetGenderCompleted;
        
        /// <remarks/>
        public event FDWSGetProductGroupCompletedEventHandler FDWSGetProductGroupCompleted;
        
        /// <remarks/>
        public event FDWSGetMaterialCompletedEventHandler FDWSGetMaterialCompleted;
        
        /// <remarks/>
        public event FDWSGetColorCompletedEventHandler FDWSGetColorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSQuickSearch", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSQuickSearch(string auth, string quickSearch) {
            object[] results = this.Invoke("FDWSQuickSearch", new object[] {
                        auth,
                        quickSearch});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSQuickSearchAsync(string auth, string quickSearch) {
            this.FDWSQuickSearchAsync(auth, quickSearch, null);
        }
        
        /// <remarks/>
        public void FDWSQuickSearchAsync(string auth, string quickSearch, object userState) {
            if ((this.FDWSQuickSearchOperationCompleted == null)) {
                this.FDWSQuickSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSQuickSearchOperationCompleted);
            }
            this.InvokeAsync("FDWSQuickSearch", new object[] {
                        auth,
                        quickSearch}, this.FDWSQuickSearchOperationCompleted, userState);
        }
        
        private void OnFDWSQuickSearchOperationCompleted(object arg) {
            if ((this.FDWSQuickSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSQuickSearchCompleted(this, new FDWSQuickSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetStyleByCollectionID", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetStyleByCollectionID(string auth, string collectionID) {
            object[] results = this.Invoke("FDWSGetStyleByCollectionID", new object[] {
                        auth,
                        collectionID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetStyleByCollectionIDAsync(string auth, string collectionID) {
            this.FDWSGetStyleByCollectionIDAsync(auth, collectionID, null);
        }
        
        /// <remarks/>
        public void FDWSGetStyleByCollectionIDAsync(string auth, string collectionID, object userState) {
            if ((this.FDWSGetStyleByCollectionIDOperationCompleted == null)) {
                this.FDWSGetStyleByCollectionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetStyleByCollectionIDOperationCompleted);
            }
            this.InvokeAsync("FDWSGetStyleByCollectionID", new object[] {
                        auth,
                        collectionID}, this.FDWSGetStyleByCollectionIDOperationCompleted, userState);
        }
        
        private void OnFDWSGetStyleByCollectionIDOperationCompleted(object arg) {
            if ((this.FDWSGetStyleByCollectionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetStyleByCollectionIDCompleted(this, new FDWSGetStyleByCollectionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSAuthenticate", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSAuthenticate(string partnerID, string subscriber) {
            object[] results = this.Invoke("FDWSAuthenticate", new object[] {
                        partnerID,
                        subscriber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSAuthenticateAsync(string partnerID, string subscriber) {
            this.FDWSAuthenticateAsync(partnerID, subscriber, null);
        }
        
        /// <remarks/>
        public void FDWSAuthenticateAsync(string partnerID, string subscriber, object userState) {
            if ((this.FDWSAuthenticateOperationCompleted == null)) {
                this.FDWSAuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSAuthenticateOperationCompleted);
            }
            this.InvokeAsync("FDWSAuthenticate", new object[] {
                        partnerID,
                        subscriber}, this.FDWSAuthenticateOperationCompleted, userState);
        }
        
        private void OnFDWSAuthenticateOperationCompleted(object arg) {
            if ((this.FDWSAuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSAuthenticateCompleted(this, new FDWSAuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSAuthenticateForPMS", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSAuthenticateForPMS(string partnerID, string subscriber, string locations, string bzipcode, string szipcode) {
            object[] results = this.Invoke("FDWSAuthenticateForPMS", new object[] {
                        partnerID,
                        subscriber,
                        locations,
                        bzipcode,
                        szipcode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSAuthenticateForPMSAsync(string partnerID, string subscriber, string locations, string bzipcode, string szipcode) {
            this.FDWSAuthenticateForPMSAsync(partnerID, subscriber, locations, bzipcode, szipcode, null);
        }
        
        /// <remarks/>
        public void FDWSAuthenticateForPMSAsync(string partnerID, string subscriber, string locations, string bzipcode, string szipcode, object userState) {
            if ((this.FDWSAuthenticateForPMSOperationCompleted == null)) {
                this.FDWSAuthenticateForPMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSAuthenticateForPMSOperationCompleted);
            }
            this.InvokeAsync("FDWSAuthenticateForPMS", new object[] {
                        partnerID,
                        subscriber,
                        locations,
                        bzipcode,
                        szipcode}, this.FDWSAuthenticateForPMSOperationCompleted, userState);
        }
        
        private void OnFDWSAuthenticateForPMSOperationCompleted(object arg) {
            if ((this.FDWSAuthenticateForPMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSAuthenticateForPMSCompleted(this, new FDWSAuthenticateForPMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetStyleColorsByStyleID", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetStyleColorsByStyleID(string auth, string StyleID) {
            object[] results = this.Invoke("FDWSGetStyleColorsByStyleID", new object[] {
                        auth,
                        StyleID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetStyleColorsByStyleIDAsync(string auth, string StyleID) {
            this.FDWSGetStyleColorsByStyleIDAsync(auth, StyleID, null);
        }
        
        /// <remarks/>
        public void FDWSGetStyleColorsByStyleIDAsync(string auth, string StyleID, object userState) {
            if ((this.FDWSGetStyleColorsByStyleIDOperationCompleted == null)) {
                this.FDWSGetStyleColorsByStyleIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetStyleColorsByStyleIDOperationCompleted);
            }
            this.InvokeAsync("FDWSGetStyleColorsByStyleID", new object[] {
                        auth,
                        StyleID}, this.FDWSGetStyleColorsByStyleIDOperationCompleted, userState);
        }
        
        private void OnFDWSGetStyleColorsByStyleIDOperationCompleted(object arg) {
            if ((this.FDWSGetStyleColorsByStyleIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetStyleColorsByStyleIDCompleted(this, new FDWSGetStyleColorsByStyleIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetStyleConfigurationsByStyleID", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetStyleConfigurationsByStyleID(string auth, string StyleID) {
            object[] results = this.Invoke("FDWSGetStyleConfigurationsByStyleID", new object[] {
                        auth,
                        StyleID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetStyleConfigurationsByStyleIDAsync(string auth, string StyleID) {
            this.FDWSGetStyleConfigurationsByStyleIDAsync(auth, StyleID, null);
        }
        
        /// <remarks/>
        public void FDWSGetStyleConfigurationsByStyleIDAsync(string auth, string StyleID, object userState) {
            if ((this.FDWSGetStyleConfigurationsByStyleIDOperationCompleted == null)) {
                this.FDWSGetStyleConfigurationsByStyleIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetStyleConfigurationsByStyleIDOperationCompleted);
            }
            this.InvokeAsync("FDWSGetStyleConfigurationsByStyleID", new object[] {
                        auth,
                        StyleID}, this.FDWSGetStyleConfigurationsByStyleIDOperationCompleted, userState);
        }
        
        private void OnFDWSGetStyleConfigurationsByStyleIDOperationCompleted(object arg) {
            if ((this.FDWSGetStyleConfigurationsByStyleIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetStyleConfigurationsByStyleIDCompleted(this, new FDWSGetStyleConfigurationsByStyleIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSgetStylesByIDs", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSgetStylesByIDs(string auth, string manufacturerID, string brandID, string collectionID, string styleID, string productGroupID, string materialID, string ageID, string genderID, string colorID, string minEyeSize, string maxEyeSize) {
            object[] results = this.Invoke("FDWSgetStylesByIDs", new object[] {
                        auth,
                        manufacturerID,
                        brandID,
                        collectionID,
                        styleID,
                        productGroupID,
                        materialID,
                        ageID,
                        genderID,
                        colorID,
                        minEyeSize,
                        maxEyeSize});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSgetStylesByIDsAsync(string auth, string manufacturerID, string brandID, string collectionID, string styleID, string productGroupID, string materialID, string ageID, string genderID, string colorID, string minEyeSize, string maxEyeSize) {
            this.FDWSgetStylesByIDsAsync(auth, manufacturerID, brandID, collectionID, styleID, productGroupID, materialID, ageID, genderID, colorID, minEyeSize, maxEyeSize, null);
        }
        
        /// <remarks/>
        public void FDWSgetStylesByIDsAsync(string auth, string manufacturerID, string brandID, string collectionID, string styleID, string productGroupID, string materialID, string ageID, string genderID, string colorID, string minEyeSize, string maxEyeSize, object userState) {
            if ((this.FDWSgetStylesByIDsOperationCompleted == null)) {
                this.FDWSgetStylesByIDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSgetStylesByIDsOperationCompleted);
            }
            this.InvokeAsync("FDWSgetStylesByIDs", new object[] {
                        auth,
                        manufacturerID,
                        brandID,
                        collectionID,
                        styleID,
                        productGroupID,
                        materialID,
                        ageID,
                        genderID,
                        colorID,
                        minEyeSize,
                        maxEyeSize}, this.FDWSgetStylesByIDsOperationCompleted, userState);
        }
        
        private void OnFDWSgetStylesByIDsOperationCompleted(object arg) {
            if ((this.FDWSgetStylesByIDsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSgetStylesByIDsCompleted(this, new FDWSgetStylesByIDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetStyleConfigurationUpdates", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetStyleConfigurationUpdates(string auth, string manufacturerID, string updateSinceDate, string filterByID, string filterType) {
            object[] results = this.Invoke("FDWSGetStyleConfigurationUpdates", new object[] {
                        auth,
                        manufacturerID,
                        updateSinceDate,
                        filterByID,
                        filterType});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetStyleConfigurationUpdatesAsync(string auth, string manufacturerID, string updateSinceDate, string filterByID, string filterType) {
            this.FDWSGetStyleConfigurationUpdatesAsync(auth, manufacturerID, updateSinceDate, filterByID, filterType, null);
        }
        
        /// <remarks/>
        public void FDWSGetStyleConfigurationUpdatesAsync(string auth, string manufacturerID, string updateSinceDate, string filterByID, string filterType, object userState) {
            if ((this.FDWSGetStyleConfigurationUpdatesOperationCompleted == null)) {
                this.FDWSGetStyleConfigurationUpdatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetStyleConfigurationUpdatesOperationCompleted);
            }
            this.InvokeAsync("FDWSGetStyleConfigurationUpdates", new object[] {
                        auth,
                        manufacturerID,
                        updateSinceDate,
                        filterByID,
                        filterType}, this.FDWSGetStyleConfigurationUpdatesOperationCompleted, userState);
        }
        
        private void OnFDWSGetStyleConfigurationUpdatesOperationCompleted(object arg) {
            if ((this.FDWSGetStyleConfigurationUpdatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetStyleConfigurationUpdatesCompleted(this, new FDWSGetStyleConfigurationUpdatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetStylePropertiesByStyleID", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetStylePropertiesByStyleID(string auth, string StyleID) {
            object[] results = this.Invoke("FDWSGetStylePropertiesByStyleID", new object[] {
                        auth,
                        StyleID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetStylePropertiesByStyleIDAsync(string auth, string StyleID) {
            this.FDWSGetStylePropertiesByStyleIDAsync(auth, StyleID, null);
        }
        
        /// <remarks/>
        public void FDWSGetStylePropertiesByStyleIDAsync(string auth, string StyleID, object userState) {
            if ((this.FDWSGetStylePropertiesByStyleIDOperationCompleted == null)) {
                this.FDWSGetStylePropertiesByStyleIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetStylePropertiesByStyleIDOperationCompleted);
            }
            this.InvokeAsync("FDWSGetStylePropertiesByStyleID", new object[] {
                        auth,
                        StyleID}, this.FDWSGetStylePropertiesByStyleIDOperationCompleted, userState);
        }
        
        private void OnFDWSGetStylePropertiesByStyleIDOperationCompleted(object arg) {
            if ((this.FDWSGetStylePropertiesByStyleIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetStylePropertiesByStyleIDCompleted(this, new FDWSGetStylePropertiesByStyleIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetCollectionsByBrandID", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetCollectionsByBrandID(string auth, string brandID) {
            object[] results = this.Invoke("FDWSGetCollectionsByBrandID", new object[] {
                        auth,
                        brandID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetCollectionsByBrandIDAsync(string auth, string brandID) {
            this.FDWSGetCollectionsByBrandIDAsync(auth, brandID, null);
        }
        
        /// <remarks/>
        public void FDWSGetCollectionsByBrandIDAsync(string auth, string brandID, object userState) {
            if ((this.FDWSGetCollectionsByBrandIDOperationCompleted == null)) {
                this.FDWSGetCollectionsByBrandIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetCollectionsByBrandIDOperationCompleted);
            }
            this.InvokeAsync("FDWSGetCollectionsByBrandID", new object[] {
                        auth,
                        brandID}, this.FDWSGetCollectionsByBrandIDOperationCompleted, userState);
        }
        
        private void OnFDWSGetCollectionsByBrandIDOperationCompleted(object arg) {
            if ((this.FDWSGetCollectionsByBrandIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetCollectionsByBrandIDCompleted(this, new FDWSGetCollectionsByBrandIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetBrandsByManufacturerID", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetBrandsByManufacturerID(string auth, string manufacturerID) {
            object[] results = this.Invoke("FDWSGetBrandsByManufacturerID", new object[] {
                        auth,
                        manufacturerID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetBrandsByManufacturerIDAsync(string auth, string manufacturerID) {
            this.FDWSGetBrandsByManufacturerIDAsync(auth, manufacturerID, null);
        }
        
        /// <remarks/>
        public void FDWSGetBrandsByManufacturerIDAsync(string auth, string manufacturerID, object userState) {
            if ((this.FDWSGetBrandsByManufacturerIDOperationCompleted == null)) {
                this.FDWSGetBrandsByManufacturerIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetBrandsByManufacturerIDOperationCompleted);
            }
            this.InvokeAsync("FDWSGetBrandsByManufacturerID", new object[] {
                        auth,
                        manufacturerID}, this.FDWSGetBrandsByManufacturerIDOperationCompleted, userState);
        }
        
        private void OnFDWSGetBrandsByManufacturerIDOperationCompleted(object arg) {
            if ((this.FDWSGetBrandsByManufacturerIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetBrandsByManufacturerIDCompleted(this, new FDWSGetBrandsByManufacturerIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetManufacturers", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetManufacturers(string auth) {
            object[] results = this.Invoke("FDWSGetManufacturers", new object[] {
                        auth});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetManufacturersAsync(string auth) {
            this.FDWSGetManufacturersAsync(auth, null);
        }
        
        /// <remarks/>
        public void FDWSGetManufacturersAsync(string auth, object userState) {
            if ((this.FDWSGetManufacturersOperationCompleted == null)) {
                this.FDWSGetManufacturersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetManufacturersOperationCompleted);
            }
            this.InvokeAsync("FDWSGetManufacturers", new object[] {
                        auth}, this.FDWSGetManufacturersOperationCompleted, userState);
        }
        
        private void OnFDWSGetManufacturersOperationCompleted(object arg) {
            if ((this.FDWSGetManufacturersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetManufacturersCompleted(this, new FDWSGetManufacturersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetAge", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetAge(string auth) {
            object[] results = this.Invoke("FDWSGetAge", new object[] {
                        auth});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetAgeAsync(string auth) {
            this.FDWSGetAgeAsync(auth, null);
        }
        
        /// <remarks/>
        public void FDWSGetAgeAsync(string auth, object userState) {
            if ((this.FDWSGetAgeOperationCompleted == null)) {
                this.FDWSGetAgeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetAgeOperationCompleted);
            }
            this.InvokeAsync("FDWSGetAge", new object[] {
                        auth}, this.FDWSGetAgeOperationCompleted, userState);
        }
        
        private void OnFDWSGetAgeOperationCompleted(object arg) {
            if ((this.FDWSGetAgeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetAgeCompleted(this, new FDWSGetAgeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetGender", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetGender(string auth) {
            object[] results = this.Invoke("FDWSGetGender", new object[] {
                        auth});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetGenderAsync(string auth) {
            this.FDWSGetGenderAsync(auth, null);
        }
        
        /// <remarks/>
        public void FDWSGetGenderAsync(string auth, object userState) {
            if ((this.FDWSGetGenderOperationCompleted == null)) {
                this.FDWSGetGenderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetGenderOperationCompleted);
            }
            this.InvokeAsync("FDWSGetGender", new object[] {
                        auth}, this.FDWSGetGenderOperationCompleted, userState);
        }
        
        private void OnFDWSGetGenderOperationCompleted(object arg) {
            if ((this.FDWSGetGenderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetGenderCompleted(this, new FDWSGetGenderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetProductGroup", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetProductGroup(string auth) {
            object[] results = this.Invoke("FDWSGetProductGroup", new object[] {
                        auth});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetProductGroupAsync(string auth) {
            this.FDWSGetProductGroupAsync(auth, null);
        }
        
        /// <remarks/>
        public void FDWSGetProductGroupAsync(string auth, object userState) {
            if ((this.FDWSGetProductGroupOperationCompleted == null)) {
                this.FDWSGetProductGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetProductGroupOperationCompleted);
            }
            this.InvokeAsync("FDWSGetProductGroup", new object[] {
                        auth}, this.FDWSGetProductGroupOperationCompleted, userState);
        }
        
        private void OnFDWSGetProductGroupOperationCompleted(object arg) {
            if ((this.FDWSGetProductGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetProductGroupCompleted(this, new FDWSGetProductGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetMaterial", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetMaterial(string auth) {
            object[] results = this.Invoke("FDWSGetMaterial", new object[] {
                        auth});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetMaterialAsync(string auth) {
            this.FDWSGetMaterialAsync(auth, null);
        }
        
        /// <remarks/>
        public void FDWSGetMaterialAsync(string auth, object userState) {
            if ((this.FDWSGetMaterialOperationCompleted == null)) {
                this.FDWSGetMaterialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetMaterialOperationCompleted);
            }
            this.InvokeAsync("FDWSGetMaterial", new object[] {
                        auth}, this.FDWSGetMaterialOperationCompleted, userState);
        }
        
        private void OnFDWSGetMaterialOperationCompleted(object arg) {
            if ((this.FDWSGetMaterialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetMaterialCompleted(this, new FDWSGetMaterialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.framesdata.com/FDWS/FDWSGetColor", RequestNamespace="http://www.framesdata.com/FDWS/", ResponseNamespace="http://www.framesdata.com/FDWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FDWSGetColor(string auth) {
            object[] results = this.Invoke("FDWSGetColor", new object[] {
                        auth});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void FDWSGetColorAsync(string auth) {
            this.FDWSGetColorAsync(auth, null);
        }
        
        /// <remarks/>
        public void FDWSGetColorAsync(string auth, object userState) {
            if ((this.FDWSGetColorOperationCompleted == null)) {
                this.FDWSGetColorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFDWSGetColorOperationCompleted);
            }
            this.InvokeAsync("FDWSGetColor", new object[] {
                        auth}, this.FDWSGetColorOperationCompleted, userState);
        }
        
        private void OnFDWSGetColorOperationCompleted(object arg) {
            if ((this.FDWSGetColorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FDWSGetColorCompleted(this, new FDWSGetColorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSQuickSearchCompletedEventHandler(object sender, FDWSQuickSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSQuickSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSQuickSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetStyleByCollectionIDCompletedEventHandler(object sender, FDWSGetStyleByCollectionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetStyleByCollectionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetStyleByCollectionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSAuthenticateCompletedEventHandler(object sender, FDWSAuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSAuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSAuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSAuthenticateForPMSCompletedEventHandler(object sender, FDWSAuthenticateForPMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSAuthenticateForPMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSAuthenticateForPMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetStyleColorsByStyleIDCompletedEventHandler(object sender, FDWSGetStyleColorsByStyleIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetStyleColorsByStyleIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetStyleColorsByStyleIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetStyleConfigurationsByStyleIDCompletedEventHandler(object sender, FDWSGetStyleConfigurationsByStyleIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetStyleConfigurationsByStyleIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetStyleConfigurationsByStyleIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSgetStylesByIDsCompletedEventHandler(object sender, FDWSgetStylesByIDsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSgetStylesByIDsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSgetStylesByIDsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetStyleConfigurationUpdatesCompletedEventHandler(object sender, FDWSGetStyleConfigurationUpdatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetStyleConfigurationUpdatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetStyleConfigurationUpdatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetStylePropertiesByStyleIDCompletedEventHandler(object sender, FDWSGetStylePropertiesByStyleIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetStylePropertiesByStyleIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetStylePropertiesByStyleIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetCollectionsByBrandIDCompletedEventHandler(object sender, FDWSGetCollectionsByBrandIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetCollectionsByBrandIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetCollectionsByBrandIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetBrandsByManufacturerIDCompletedEventHandler(object sender, FDWSGetBrandsByManufacturerIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetBrandsByManufacturerIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetBrandsByManufacturerIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetManufacturersCompletedEventHandler(object sender, FDWSGetManufacturersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetManufacturersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetManufacturersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetAgeCompletedEventHandler(object sender, FDWSGetAgeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetAgeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetAgeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetGenderCompletedEventHandler(object sender, FDWSGetGenderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetGenderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetGenderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetProductGroupCompletedEventHandler(object sender, FDWSGetProductGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetProductGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetProductGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetMaterialCompletedEventHandler(object sender, FDWSGetMaterialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetMaterialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetMaterialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FDWSGetColorCompletedEventHandler(object sender, FDWSGetColorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FDWSGetColorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FDWSGetColorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591